### ISSUE TITLE
Class Items

### ISSUE THREAD

**Issue by Forelius** [Forelius/fantastic-depths#32]
Create an item type for character classes. Replace use of json data from config file with data from these items. This will allow for easier addition of custom classes by GMs.

**Comment by JordanRR** [comment]
Maybe you already know (since you said it was incomplete), but 2 small things.
- There is not a way to add a level in the class Item. 
- When you delete a Saving throw row, it stays there. It appears to "refresh" only when you add another one (so you need to delete +1 row before hitting the "+" if you want the right number of rows.)

Thanks!

**Comment by Forelius** [comment]
These issues should be resolved in [v0.6.10](https://github.com/Forelius/fantastic-depths/releases/tag/v0.6.10)
